/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mylib.ui;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import mylib.util.HibernateUtil;
import mylib.entity.Links;
import mylib.entity.Authors;
import mylib.entity.Books;
/**
 *
 * @author sT3ls
 */
public class createbook extends javax.swing.JFrame {

    /**
     * Creates new form createbook
     */
    public createbook() {
        initComponents();
    }
    
    public void newbook()
    {
        Session session = null;
        try{session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        String [] str = newauthorsTextArea.getText().split("\n");
        Query booksearch = session.createQuery("from Books b where b.bookName like '"+newbookTextField.getText()+"%'");
        if (booksearch.uniqueResult()!=null)
        {
            JOptionPane.showMessageDialog(null,"This book is already added!!!");
            newbookTextField.setText("");
            newauthorsTextArea.setText("");
            return;
        }
        Books book = new Books(newbookTextField.getText(),"free");
        session.save(book);
        for(int i=0;i<newauthorsTextArea.getLineCount();i++)
        {
            
            Links links  = new Links();
            links.setBooks(book);
            Query q = session.createQuery("from Authors a where a.authorName like '"+str[i]+"%'");
            if(q.uniqueResult()!=null)
            {
                Authors authorrep = (Authors) q.uniqueResult();
                links.setAuthors(authorrep);
                session.save(authorrep);
                authorrep = null;
            }
            else{
            Authors author = new Authors(str[i]);
            links.setAuthors(author);
            session.save(author);
            author = null;}
            session.save(links);
        }
        session.getTransaction().commit();
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            if (session != null) session.getTransaction().rollback();
        } finally {
            if (session != null && session.isOpen()) {
 
                session.close();
            }
    }
        JOptionPane.showMessageDialog(null,"Book added!!!");
        newbookTextField.setText("");
        newauthorsTextArea.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newbookTextField = new javax.swing.JTextField();
        createnewbookBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        newauthorsTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Книга");

        jLabel2.setText("Авторы");

        createnewbookBtn.setText("Добавить");
        createnewbookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createnewbookBtnActionPerformed(evt);
            }
        });

        newauthorsTextArea.setColumns(20);
        newauthorsTextArea.setRows(5);
        newauthorsTextArea.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane2.setViewportView(newauthorsTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createnewbookBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(newbookTextField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newbookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createnewbookBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createnewbookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createnewbookBtnActionPerformed
        // TODO add your handling code here:
        newbook();
    }//GEN-LAST:event_createnewbookBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void showframe() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createbook().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createnewbookBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea newauthorsTextArea;
    private javax.swing.JTextField newbookTextField;
    // End of variables declaration//GEN-END:variables
}
