package mylib.entity;
// Generated 04.10.2012 18:41:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private Integer idBook;
     private String bookName;
     private String status;
     private Set linkses = new HashSet(0);

    public Books() {
    }

	
    public Books(String bookName, String status) {
        this.bookName = bookName;
        this.status = status;
    }
    public Books(String bookName, String status, Set linkses) {
       this.bookName = bookName;
       this.status = status;
       this.linkses = linkses;
    }
   
    public Integer getIdBook() {
        return this.idBook;
    }
    
    public void setIdBook(Integer idBook) {
        this.idBook = idBook;
    }
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getLinkses() {
        return this.linkses;
    }
    
    public void setLinkses(Set linkses) {
        this.linkses = linkses;
    }




}


